### ISSUE TITLE
IntelliJ IDEA 201.5985.32  版本报错

### ISSUE THREAD

**Issue by yaolj4168** [makejavas/EasyCode#22]
IntelliJ IDEA 201.5985.32  版本报错

**Comment by makejavas** [comment]
请提供具体报错信息

**Comment by cn-src** [comment]
在打开设置时会出现以下错误，并且导致设置窗口打不开。
```
Cannot get children Easy Code

java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at com.sjhy.plugin.ui.TypeMapperSetting.$$$setupUI$$$(TypeMapperSetting.java)
	at com.sjhy.plugin.ui.TypeMapperSetting.<init>(TypeMapperSetting.java:83)
	at com.sjhy.plugin.ui.MainSetting.getConfigurables(MainSetting.java:332)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:276)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:128)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.collect(EpBasedConfigurableGroup.kt:137)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroupKt.access$collect(EpBasedConfigurableGroup.kt:1)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:100)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:127)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:50)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
	
```

**Comment by makejavas** [comment]
可能是版本太新了照成的，尚未进行向上兼容。

**Comment by yaolj4168** [comment]
现在最新版idea 也有了，向上兼容版，什么时候发布？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"makejavas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 凌晨0:00
收件人:&nbsp;"makejavas/EasyCode"<EasyCode@noreply.github.com&gt;;
抄送:&nbsp;"ツ天使之翼ゞ"<176743650@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [makejavas/EasyCode] IntelliJ IDEA 201.5985.32  版本报错 (#22)





 
可能是版本太新了照成的，尚未进行向上兼容。

**Comment by zxiaozhou** [comment]
现在我更新到idea2020后会导致mac平台无法打开设置，打开直接报错，日志如下,只要启动easycode就会出现下面日志，且无法打开设置(通过直接点击plugins禁用后一切正常)：
```
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1



java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:150)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:645)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:396)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:379)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
	at com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent.initComponent(CommonSettingsApplicationComponent.kt:40)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:261)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:334)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:334)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:184)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:416)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by makejavas** [comment]
暂时尚未兼容新版本的IDEA，感谢您的建议。将会在未来版本做兼容。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zxiaozhou"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 晚上11:04
收件人: "makejavas/EasyCode"<EasyCode@noreply.github.com&gt;; 
抄送: "makejava"<1353036300@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [makejavas/EasyCode] IntelliJ IDEA 201.5985.32  版本报错 (#22)





 
现在我更新到idea2020后会导致mac平台无法打开设置，打开直接报错，日志如下,只要启动easycode就会出现下面日志，且无法打开设置(通过直接点击plugins禁用后一切正常)：
 Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED Current violators count: 1 java.lang.Throwable 	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56) 	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52) 	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init&gt;(ActionManagerImpl.java:150) 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) 	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48) 	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:645) 	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:54) 	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15) 	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47) 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625) 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570) 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61) 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186) 	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46) 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115) 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69) 	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:396) 	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:379) 	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28) 	at com.alibaba.p3c.idea.component.CommonSettingsApplicationComponent.initComponent(CommonSettingsApplicationComponent.kt:40) 	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:46) 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115) 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69) 	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62) 	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:261) 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:334) 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164) 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625) 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570) 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61) 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151) 	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:334) 	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:184) 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201) 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831) 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310) 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80) 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128) 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46) 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184) 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:416) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by zxiaozhou** [comment]
还麻烦尽快兼容，，现在用不了很老火。。。

**Comment by cn-src** [comment]
> 还麻烦尽快兼容，，现在用不了很老火。。。

淡定。idea 2020.1正式版也才刚发布。只要项目还在维护中就行。

**Comment by makejavas** [comment]
稍等，正在处理中

**Comment by makejavas** [comment]
查看[已解决版本](https://github.com/makejavas/EasyCode/releases/tag/EasyCode-1.2.3)

**Comment by zxiaozhou** [comment]
非常感谢
