### ISSUE TITLE
插件不能使用，报 NullPointerException

### ISSUE THREAD

**Issue by vicasong** [makejavas/EasyCode#33]
##  版本信息  

> IntelliJ IDEA 2020.1 (Ultimate Edition) Build #IU-201.6668.121, built on April 8, 2020
> Easy Code 1.2.3-RELEASE

## 操作方式  

> 在"Database"工具窗口选择多个数据表 -> 右键"Easy Code" -> "Genorate Code"  

该操作无效，Idea提示插件异常错误 

## 错误信息  

```  
java.lang.NullPointerException
	at com.sjhy.plugin.ui.SelectSavePath.getBasePath(SelectSavePath.java:363)
	at com.sjhy.plugin.ui.SelectSavePath.refreshPath(SelectSavePath.java:374)
	at com.sjhy.plugin.ui.SelectSavePath.lambda$init$8(SelectSavePath.java:256)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:589)
	at com.sjhy.plugin.ui.SelectSavePath.init(SelectSavePath.java:325)
	at com.sjhy.plugin.ui.SelectSavePath.<init>(SelectSavePath.java:138)
	at com.sjhy.plugin.actions.MainAction.actionPerformed(MainAction.java:46)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by vicasong** [comment]
## 补充 

即使选择单个数据表也无法使用

**Comment by makejavas** [comment]
去.idea/EasyCodeConfig目录下找到不能生成的表对应的配置文件，删除即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"vicasong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 上午9:51
收件人:&nbsp;"makejavas/EasyCode"<EasyCode@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[makejavas/EasyCode] 插件不能使用，报 NullPointerException (#33)





 
版本信息
  
IntelliJ IDEA 2020.1 (Ultimate Edition) Build #IU-201.6668.121, built on April 8, 2020
 Easy Code 1.2.3-RELEASE
  
操作方式
  
在"Database"工具窗口选择多个数据表 -&gt; 右键"Easy Code" -&gt; "Genorate Code"
  
该操作无效，Idea提示插件异常错误
 
错误信息
 java.lang.NullPointerException 	at com.sjhy.plugin.ui.SelectSavePath.getBasePath(SelectSavePath.java:363) 	at com.sjhy.plugin.ui.SelectSavePath.refreshPath(SelectSavePath.java:374) 	at com.sjhy.plugin.ui.SelectSavePath.lambda$init$8(SelectSavePath.java:256) 	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264) 	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:589) 	at com.sjhy.plugin.ui.SelectSavePath.init(SelectSavePath.java:325) 	at com.sjhy.plugin.ui.SelectSavePath.<init&gt;(SelectSavePath.java:138) 	at com.sjhy.plugin.actions.MainAction.actionPerformed(MainAction.java:46) 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280) 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296) 	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281) 	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77) 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285) 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112) 	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94) 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112) 	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517) 	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36) 	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539) 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651) 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345) 	at java.desktop/java.awt.Component.processEvent(Component.java:6416) 	at java.desktop/java.awt.Container.processEvent(Container.java:2263) 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026) 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858) 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773) 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858) 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751) 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748) 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974) 	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912) 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844) 	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449) 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739) 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448) 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831) 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by makejavas** [comment]
尝试使用[1.2.4内测版](http://www.shujuhaiyang.com/)
