### ISSUE TITLE
读取配置失败,JSON反序列化失败

### ISSUE THREAD

**Issue by BenjaminFyang** [makejavas/EasyCode#65]
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "originTableName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
 at [Source: (String)"{
  "name" : "OmsOrder",
  "originTableName" : "oms_order",
  "comment" : "订单表",
  "fullColumn" : [ {
    "name" : "id",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "ktShortType" : "Long",
    "custom" : false,
    "ext" : { }
  }, {
    "name" : "memberId",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "ktShortType" : "Long",
    "custom" : false,
    "ext" : { }
  }, {
    "name" : "couponId",
    "comment" : null,
    "type" : null,
    "shortTy"[truncated 7113 chars]; line: 3, column: 24] (through reference chain: com.sjhy.plugin.entity.TableInfo["originTableName"])
	at com.intellij.util.ExceptionUtilRt.rethrow(ExceptionUtilRt.java:31)
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:120)
	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:385)
	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.read(TableInfoServiceImpl.java:360)
	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.loadConfig(TableInfoServiceImpl.java:139)
	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.getTableInfoAndConfig(TableInfoServiceImpl.java:125)
	at com.sjhy.plugin.ui.ConfigTableDialog.init(ConfigTableDialog.java:132)
	at com.sjhy.plugin.ui.ConfigTableDialog.<init>(ConfigTableDialog.java:101)
	at com.sjhy.plugin.actions.ConfigAction.actionPerformed(ConfigAction.java:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:522)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "originTableName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
 at [Source: (String)"{
  "name" : "OmsOrder",
  "originTableName" : "oms_order",
  "comment" : "订单表",
  "fullColumn" : [ {
    "name" : "id",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "ktShortType" : "Long",
    "custom" : false,
    "ext" : { }
  }, {
    "name" : "memberId",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "ktShortType" : "Long",
    "custom" : false,
    "ext" : { }
  }, {
    "name" : "couponId",
    "comment" : null,
    "type" : null,
    "shortTy"[truncated 7113 chars]; line: 3, column: 24] (through reference chain: com.sjhy.plugin.entity.TableInfo["originTableName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:382)
	... 56 more

**Comment by BenjaminFyang** [comment]
> java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "originTableName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
> at [Source: (String)"{
> "name" : "OmsOrder",
> "originTableName" : "oms_order",
> "comment" : "订单表",
> "fullColumn" : [ {
> "name" : "id",
> "comment" : null,
> "type" : null,
> "shortType" : null,
> "ktShortType" : "Long",
> "custom" : false,
> "ext" : { }
> }, {
> "name" : "memberId",
> "comment" : null,
> "type" : null,
> "shortType" : null,
> "ktShortType" : "Long",
> "custom" : false,
> "ext" : { }
> }, {
> "name" : "couponId",
> "comment" : null,
> "type" : null,
> "shortTy"[truncated 7113 chars]; line: 3, column: 24] (through reference chain: com.sjhy.plugin.entity.TableInfo["originTableName"])
> at com.intellij.util.ExceptionUtilRt.rethrow(ExceptionUtilRt.java:31)
> at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:120)
> at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:385)
> at com.sjhy.plugin.service.impl.TableInfoServiceImpl.read(TableInfoServiceImpl.java:360)
> at com.sjhy.plugin.service.impl.TableInfoServiceImpl.loadConfig(TableInfoServiceImpl.java:139)
> at com.sjhy.plugin.service.impl.TableInfoServiceImpl.getTableInfoAndConfig(TableInfoServiceImpl.java:125)
> at com.sjhy.plugin.ui.ConfigTableDialog.init(ConfigTableDialog.java:132)
> at com.sjhy.plugin.ui.ConfigTableDialog.(ConfigTableDialog.java:101)
> at com.sjhy.plugin.actions.ConfigAction.actionPerformed(ConfigAction.java:37)
> at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
> at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
> at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
> at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
> at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
> at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
> at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
> at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:522)
> at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
> at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
> at java.awt.Component.processMouseEvent(Component.java:6548)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> at java.awt.Component.processEvent(Component.java:6313)
> at java.awt.Container.processEvent(Container.java:2237)
> at java.awt.Component.dispatchEventImpl(Component.java:4903)
> at java.awt.Container.dispatchEventImpl(Container.java:2295)
> at java.awt.Component.dispatchEvent(Component.java:4725)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> at java.awt.Container.dispatchEventImpl(Container.java:2281)
> at java.awt.Window.dispatchEventImpl(Window.java:2746)
> at java.awt.Component.dispatchEvent(Component.java:4725)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> at java.awt.EventQueue.access$500(EventQueue.java:98)
> at java.awt.EventQueue$3.run(EventQueue.java:715)
> at java.awt.EventQueue$3.run(EventQueue.java:709)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> at java.awt.EventQueue$4.run(EventQueue.java:737)
> at java.awt.EventQueue$4.run(EventQueue.java:735)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
> at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
> at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "originTableName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
> at [Source: (String)"{
> "name" : "OmsOrder",
> "originTableName" : "oms_order",
> "comment" : "订单表",
> "fullColumn" : [ {
> "name" : "id",
> "comment" : null,
> "type" : null,
> "shortType" : null,
> "ktShortType" : "Long",
> "custom" : false,
> "ext" : { }
> }, {
> "name" : "memberId",
> "comment" : null,
> "type" : null,
> "shortType" : null,
> "ktShortType" : "Long",
> "custom" : false,
> "ext" : { }
> }, {
> "name" : "couponId",
> "comment" : null,
> "type" : null,
> "shortTy"[truncated 7113 chars]; line: 3, column: 24] (through reference chain: com.sjhy.plugin.entity.TableInfo["originTableName"])
> at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
> at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
> at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
> at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
> at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
> at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
> at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
> at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
> at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:382)
> ... 56 more
-- auto-generated definition
create table oms_order
(
  id                      bigint auto_increment comment '订单id'
    primary key,
  member_id               bigint         not null,
  coupon_id               bigint         null,
  order_sn                varchar(64)    null comment '订单编号',
  create_time             datetime       null comment '提交时间',
  member_username         varchar(64)    null comment '用户帐号',
  total_amount            decimal(10, 2) null comment '订单总金额',
  pay_amount              decimal(10, 2) null comment '应付金额（实际支付金额）',
  freight_amount          decimal(10, 2) null comment '运费金额',
  promotion_amount        decimal(10, 2) null comment '促销优化金额（促销价、满减、阶梯价）',
  integration_amount      decimal(10, 2) null comment '积分抵扣金额',
  coupon_amount           decimal(10, 2) null comment '优惠券抵扣金额',
  discount_amount         decimal(10, 2) null comment '管理员后台调整订单使用的折扣金额',
  pay_type                int            null comment '支付方式：0->未支付；1->支付宝；2->微信',
  source_type             int            null comment '订单来源：0->PC订单；1->app订单',
  status                  int            null comment '订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单',
  order_type              int            null comment '订单类型：0->正常订单；1->秒杀订单',
  delivery_company        varchar(64)    null comment '物流公司(配送方式)',
  delivery_sn             varchar(64)    null comment '物流单号',
  auto_confirm_day        int            null comment '自动确认时间（天）',
  integration             int            null comment '可以获得的积分',
  growth                  int            null comment '可以活动的成长值',
  promotion_info          varchar(100)   null comment '活动信息',
  bill_type               int            null comment '发票类型：0->不开发票；1->电子发票；2->纸质发票',
  bill_header             varchar(200)   null comment '发票抬头',
  bill_content            varchar(200)   null comment '发票内容',
  bill_receiver_phone     varchar(32)    null comment '收票人电话',
  bill_receiver_email     varchar(64)    null comment '收票人邮箱',
  receiver_name           varchar(100)   not null comment '收货人姓名',
  receiver_phone          varchar(32)    not null comment '收货人电话',
  receiver_post_code      varchar(32)    null comment '收货人邮编',
  receiver_province       varchar(32)    null comment '省份/直辖市',
  receiver_city           varchar(32)    null comment '城市',
  receiver_region         varchar(32)    null comment '区',
  receiver_detail_address varchar(200)   null comment '详细地址',
  note                    varchar(500)   null comment '订单备注',
  confirm_status          int            null comment '确认收货状态：0->未确认；1->已确认',
  delete_status           int default 0  not null comment '删除状态：0->未删除；1->已删除',
  use_integration         int            null comment '下单时使用的积分',
  payment_time            datetime       null comment '支付时间',
  delivery_time           datetime       null comment '发货时间',
  receive_time            datetime       null comment '确认收货时间',
  comment_time            datetime       null comment '评价时间',
  modify_time             datetime       null comment '修改时间'
)
  comment '订单表';

**Comment by hcw2175** [comment]
我也遇到一样问题。

IDEA版本：2019.3
EasyCode版本：EasyCode-1.2.3-RELEASE
安装方式：手动安装插件

mysql表结构：

```
-- 中国行政区划数据管理
DROP TABLE IF EXISTS confdata_china_region;
CREATE TABLE confdata_china_region
(
  id            bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  parent_adcode varchar(50) COMMENT '所属上级区域编码',
  adcode        varchar(50) COMMENT '区域编码',
  name          varchar(100) COMMENT '区域名称',
  citycode      varchar(50) COMMENT '城市编码',
  level         varchar(20) COMMENT '区域级别：country:国家|province:省份|city:市|district:区县|street:街道',
  center        varchar(255) COMMENT '区域中心点',
  PRIMARY KEY (id)
) COMMENT = '中国行政区划数据管理';
```

错误信息：

```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "preName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
 at [Source: (String)"{
  "name" : "ConfdataChinaRegion",
  "preName" : "",
  "comment" : "中国行政区划数据管理",
  "templateGroupName" : "Default",
  "fullColumn" : [ {
    "name" : "id",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "custom" : false,
    "ext" : { }
  }, {
    "name" : "parentAdcode",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "custom" : false,
    "ext" : { }
  }, {
    "name" : "adcode",
    "comment" : null,
    "type" : null,
    "shortType" : null,
    "c"[truncated 846 chars]; line: 3, column: 16] (through reference chain: com.sjhy.plugin.entity.TableInfo["preName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:382)
	... 58 more
2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.3.5  Build #IU-193.7288.26 
2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Easy Code version: 1.2.3-RELEASE 
2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - Last Action: com.sjhy.easy.code.action.generate 
2021-04-22 14:37:09,338 [3559232]   INFO - nSession$CountedThreadExecutor - DbSrcWriter stopped 
```

**Comment by hcw2175** [comment]
> 我也遇到一样问题。
> 
> IDEA版本：2019.3
> EasyCode版本：EasyCode-1.2.3-RELEASE
> 安装方式：手动安装插件
> 
> mysql表结构：
> 
> ```
> -- 中国行政区划数据管理
> DROP TABLE IF EXISTS confdata_china_region;
> CREATE TABLE confdata_china_region
> (
>   id            bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
>   parent_adcode varchar(50) COMMENT '所属上级区域编码',
>   adcode        varchar(50) COMMENT '区域编码',
>   name          varchar(100) COMMENT '区域名称',
>   citycode      varchar(50) COMMENT '城市编码',
>   level         varchar(20) COMMENT '区域级别：country:国家|province:省份|city:市|district:区县|street:街道',
>   center        varchar(255) COMMENT '区域中心点',
>   PRIMARY KEY (id)
> ) COMMENT = '中国行政区划数据管理';
> ```
> 
> 错误信息：
> 
> ```
> Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "preName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
>  at [Source: (String)"{
>   "name" : "ConfdataChinaRegion",
>   "preName" : "",
>   "comment" : "中国行政区划数据管理",
>   "templateGroupName" : "Default",
>   "fullColumn" : [ {
>     "name" : "id",
>     "comment" : null,
>     "type" : null,
>     "shortType" : null,
>     "custom" : false,
>     "ext" : { }
>   }, {
>     "name" : "parentAdcode",
>     "comment" : null,
>     "type" : null,
>     "shortType" : null,
>     "custom" : false,
>     "ext" : { }
>   }, {
>     "name" : "adcode",
>     "comment" : null,
>     "type" : null,
>     "shortType" : null,
>     "c"[truncated 846 chars]; line: 3, column: 16] (through reference chain: com.sjhy.plugin.entity.TableInfo["preName"])
> 	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
> 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
> 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
> 	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:382)
> 	... 58 more
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.3.5  Build #IU-193.7288.26 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Easy Code version: 1.2.3-RELEASE 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - Last Action: com.sjhy.easy.code.action.generate 
> 2021-04-22 14:37:09,338 [3559232]   INFO - nSession$CountedThreadExecutor - DbSrcWriter stopped 
> ```

发现表名`confdata_china_region `修改成`confdata_china_regions`就可以了，太奇怪了~

**Comment by JL-Code** [comment]
> 我也遇到一样问题。
> 
> IDEA版本：2019.3
> EasyCode版本：EasyCode-1.2.3-RELEASE
> 安装方式：手动安装插件
> 
> mysql表结构：
> 
> ```
> -- 中国行政区划数据管理
> DROP TABLE IF EXISTS confdata_china_region;
> CREATE TABLE confdata_china_region
> (
>   id            bigint UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
>   parent_adcode varchar(50) COMMENT '所属上级区域编码',
>   adcode        varchar(50) COMMENT '区域编码',
>   name          varchar(100) COMMENT '区域名称',
>   citycode      varchar(50) COMMENT '城市编码',
>   level         varchar(20) COMMENT '区域级别：country:国家|province:省份|city:市|district:区县|street:街道',
>   center        varchar(255) COMMENT '区域中心点',
>   PRIMARY KEY (id)
> ) COMMENT = '中国行政区划数据管理';
> ```
> 
> 错误信息：
> 
> ```
> Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "preName" (class com.sjhy.plugin.entity.TableInfo), not marked as ignorable (8 known properties: "pkColumn", "savePath", "savePackageName", "fullColumn", "otherColumn", "saveModelName", "name", "comment"])
>  at [Source: (String)"{
>   "name" : "ConfdataChinaRegion",
>   "preName" : "",
>   "comment" : "中国行政区划数据管理",
>   "templateGroupName" : "Default",
>   "fullColumn" : [ {
>     "name" : "id",
>     "comment" : null,
>     "type" : null,
>     "shortType" : null,
>     "custom" : false,
>     "ext" : { }
>   }, {
>     "name" : "parentAdcode",
>     "comment" : null,
>     "type" : null,
>     "shortType" : null,
>     "custom" : false,
>     "ext" : { }
>   }, {
>     "name" : "adcode",
>     "comment" : null,
>     "type" : null,
>     "shortType" : null,
>     "c"[truncated 846 chars]; line: 3, column: 16] (through reference chain: com.sjhy.plugin.entity.TableInfo["preName"])
> 	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
> 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
> 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
> 	at com.sjhy.plugin.service.impl.TableInfoServiceImpl.parser(TableInfoServiceImpl.java:382)
> 	... 58 more
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.3.5  Build #IU-193.7288.26 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Easy Code version: 1.2.3-RELEASE 
> 2021-04-22 14:37:03,981 [3553875]  ERROR - llij.ide.plugins.PluginManager - Last Action: com.sjhy.easy.code.action.generate 
> 2021-04-22 14:37:09,338 [3559232]   INFO - nSession$CountedThreadExecutor - DbSrcWriter stopped 
> ```

你们有遇到 column.obj.notNull 无法获取字段必填信息的问题吗？

**Comment by makejavas** [comment]
请升级至最新版解决，暂时先关闭问题。如问题仍然存在请重新打开。
